music/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView,ListView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static
from app.models import Song
from app.views import root,playlist,PlayNow,home
from app.ajax import  playSong
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'music.views.home', name='home'),
    # url(r'^music/', include('music.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'', include('social_auth.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', "django.contrib.auth.views.login", {"template_name": "login.html"}, name="login"),
    url(r"^logout/$", "django.contrib.auth.views.logout_then_login",name="logout"),
    url(r'^playlist/', playlist.as_view(),name="playlist"),
    url(r'search/', root.as_view()	,name="search" ),	
    url(r'^play/',login_required(PlayNow.as_view()), name="playnow"),
    url(r'^ajax/', playSong.as_view(), name="ajax"),
    url(r'^', login_required(home.as_view()), name="home")

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from djangotoolbox.fields import ListField,EmbeddedModelField
# Create your models here.
'''
class Artist(models.Model):
	name= models.CharField(max_length=20)
	bio= models.TextField()
	artist_pic= models.FileField(upload_to="artist/",blank=True)

	def __unicode__(self):
		return self.name
	
	class Meta:
		ordering = ["name"]

class Album(models.Model):
	name= models.CharField(max_length=20)
	year= models.PositiveSmallIntegerField(blank=True, null=True)
	album_art= models.FileField(upload_to="album/",blank=True)

	def __unicode__(self):
		return "%s %s" %(self.name,self.year)
'''

class Song(models.Model):
	title= models.CharField(max_length=50)
	artist=models.CharField(max_length=50)
	album= models.CharField(max_length=50)
	year=models.PositiveSmallIntegerField(blank=True, null=True)
	genre= models.CharField(max_length=50)
	views=models.PositiveSmallIntegerField(default=0)
	file= models.FileField(upload_to="songs/")

	def __unicode__(self):
		return "%s-%s-%s-%s" % (self.title,self.album,self.artist,self.views)

	class Meta:
		ordering = ["-views"]

class ArtistGroup(models.Model):
	groupName=models.CharField(max_length=20)
	songs=models.ManyToManyField(Song)

	def __unicode__(self):
		return "%s %d" % (self.groupName,self.songs.count())


class AlbumGroup(models.Model):
	groupName=models.CharField(max_length=20)
	songs=models.ManyToManyField(Song)
	album_art= models.FileField(upload_to="album/",blank=True)


	def __unicode__(self):
		return "%s %d" % (self.groupName,self.songs.count())


class GenreGroup(models.Model):
	groupName=models.CharField(max_length=20)
	songs=models.ManyToManyField(Song)

	def __unicode__(self):
		return "%s %d" % (self.groupName,self.songs.count())


class Playlist(models.Model):
	user= models.ForeignKey(User)
	name= models.CharField(max_length=50)
	songs= models.ManyToManyField(Song, related_name="playlist")
	date= models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return "%s %s %s" % (self.name,self.user,self.date)

	class Meta:
		ordering = ["name"]



class UserLog(models.Model):
	song= models.ForeignKey(Song)
	user= models.ForeignKey(User)
	time= models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return "%s %s %s" % (self.user.username, self.time,self.song.title)

	class Meta:
		ordering = ["-time"]


class Dicty(models.Model):
    name=models.TextField()

class Recommend(models.Model):
	user=models.ForeignKey(User)
	artist_rec=models.ManyToManyField(Song, related_name="artist_rec")
	album_rec= models.ManyToManyField(Song, related_name="album_rec")
	genre_rec= models.ManyToManyField(Song, related_name="genre_rec")
	friend_rec= models.ManyToManyField(Song, related_name="friend_rec")
	col_rec= models.ManyToManyField(Song, related_name="col_rec")
	#following contains only one dict in list  list=[dict{}]
	artist_preference_table= models.TextField()
	album_preference_table= models.TextField()
	genre_preference_table= models.TextField()
	diff_table= models.TextField()

	def __unicode__(self):
		return self.user.username

class User_IB(models.Model):
	user= models.ForeignKey(User)
	ib_vector= models.ManyToManyField(Dicty, related_name="id_vector")

class UserGroup(models.Model):
	groupName=models.CharField(max_length=20)
	user_list= models.ManyToManyField(User, related_name="user_list")

app/forms.py
from haystack.forms import SearchForm

class SongSearchForm(SearchForm):
	
	def no_query_found(self):
		return self.searchqueryset.all()

	def search(self):
		sqs= super(SongSearchForm,self).search()

		if not self.is_valid():
			return self.no_query_found()

		sqs= sqs.order_by('title')

		return sqs

app/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse,Http404
from django.views.generic import TemplateView,View,DetailView
from app.forms import SongSearchForm
from .models import Playlist,Song,UserLog,Recommend,AlbumGroup
import json
from itertools import chain

class root(View):

	def get(self,request):
		form= SongSearchForm(request.GET)
		results= form.search()
		return render(request,'search/search.html',
			{
				'songs' :results
			})

class PlayNow(View):

	def get(self,request):
		if request.is_ajax():
			song=Song.objects.get(id=request.GET["songId"])

			song.views+=1
			song.save()
			log=UserLog(song=song,
						user=request.user)	
			log.save()
			pic= AlbumGroup.objects.get(groupName=song.album)
			data={ 'title':song.title,'url':song.file.url,'artist':song.artist,'view':song.views,
			'album_art':pic.album_art.url}

			return HttpResponse(json.dumps(data),content_type="application/json")

		else:
			raise Http404
		

class playlist(View):

	def post(self,request):
		playlist=Playlist(user=request.user,
						  name=request.POST['name'])
		playlist.save()
		return HttpResponseRedirect("/")


class home(View):

	def get(self,request):
		song=Song.objects.all()[:10]
		rec=Recommend.objects.get(user=request.user)
		rec_list=list(chain(rec.artist_rec.all(),rec.album_rec.all(),rec.genre_rec.all()))
		template_name="home.html"
		playlist=Playlist.objects.filter(user=request.user)
		usrlog= UserLog.objects.filter(user=request.user)
		return render(request,template_name,{"songs":song,
			"rec_list":rec_list,
			"playlists":playlist,
			"userlog":usrlog})

templates/base.html
<html ng-app="music">

<head>

   <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script-->
   <script type="text/javascript" src="{{STATIC_URL}}darkly/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/music.js"></script>
    
    <link rel="stylesheet" href="{{STATIC_URL}}darkly/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="{{STATIC_URL}}darkly/bootswatch.min.css">
    <!--link rel="stylesheet" href="http://bootswatch.com/bower_components/font-awesome/css/font-awesome.min.css" media="screen"-->
   
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <!--script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script-->

    {% block title %}
    {% endblock %}
</head>
<body>



        <header class="navbar navbar-inverse navbar-fixed-top" role="banner">
      <div class="container">
        <div class="navbar-header-solid">
           <a class="navbar-brand" href="{% url 'home' %}"> <i class="fa fa-play-circle-o fa-1x"> SoundBox</i></a>
                      
        </div>
    
        <div class="col-md-6">
          <form type="get" action="/search/" class="navbar-form" role="search">
        <div class="form-group">
  <div class="input-group">
    <!--span class="input-group-addon">Search</span-->
    <input type="text" class="form-control" placeholder="Love Story,Taylor Swift" name='q'>
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit" autofocus><i>Search!</i></button>
    </span>
  </div>
  </div>
        </form>

        </div>  


           <ul class="nav navbar-nav navbar-right">
        
          {% if user.is_authenticated %}
            <li class="dropdown">
          <a  href="{% url 'home' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user"></i><b> {{ user.first_name.capitalize }} </b><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">About</a></li>
          
          </ul>
        </li>
            
	         <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i> <b>Logout</b></a></li>
    
            {% else %}
          <li><a href="{% url 'login' %}">Login</a>
              
          </li>     
           {% endif %}
                 
          </ul> </div>
      </div>
    </header>
    <!-- <br/> -->
    <br/>
   <div class="container" ng-controller="addtoplayer">
   <div class="row">
   
   
    {% block content %}
    


    {% endblock content %}

    {% block search %}

    {% endblock %}
    </div>


   </div>

 
    <!--script src="{{STATIC_URL}}darkly/jquery-1.10.2.min.js"></script-->
<script src="{{STATIC_URL}}darkly/bootstrap.min.js"></script>
 
</body>
<!--footer>
 <p>
          Built with lots of <span style="color: #C0392B;">♥</span> and little bit of Python
        </p>
</footer>
</div>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
  <title>Home -SoundBox</title>
{% endblock %}

{% block content %}

<div class="col-md-8"> 
<ul class="nav nav-tabs">
  <li class="active"><a href="#home" data-toggle="tab" aria-expanded="true">Recommended</a></li>
  <li class=""><a href="#search" data-toggle="tab" aria-expanded="false">Trending</a></li>
  <li class=""><a href="#playlist" data-toggle="tab" aria-expanded="false">My Playlists</a></li>
   <li class=""><a href="#friends" data-toggle="tab" aria-expanded="false">Friends Activity</a></li>
</ul>

<div id="myTabContent" class="tab-content">
  
 
  <div class="tab-pane fade active in" id="home">   
  {% if rec_list %}
  <div class="row">
      <div class="btn-group btn-group-justified">
  <a   data-toggle="tab" id="all_btn" href="#" class="btn btn-default">All</a>
  <a  data-toggle="tab" href="#" id="artist_btn" class="btn btn-default">Artist</a>
  <a  data-toggle="tab" href="#" id="album_btn" class="btn btn-default">Album</a>
   <a data-toggle="tab" href="#" id="genre_btn" class="btn btn-default">Genre</a>
    <a data-toggle="tab" href="#"  id="collab_btn" class="btn btn-default">Collaborative</a>
</div>
</div>
<br/>
<!--All-->
  <div class="row" id="all">    
    <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th></th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in rec_list %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

   </div><!--end of all-->

   <!--Artist-->
    <div class="row" id="artist">    
    <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th></th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in artist_list %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

   </div><!--end of Artist-->

   <!--album-->
    <div class="row" id="album">    
    <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th></th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in album_list %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

   </div><!--end of album-->
<!--genre-->
 <div class="row" id="genre">    
    <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th></th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in genre_list %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

   </div><!--end of genre-->
   <!--collab-->
    <div class="row" id="collab">    
    <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th></th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in collab_list %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

   </div><!--end of collab-->



   {% else %}
   <h3> Listen to some songs!</h3>
   {% endif %}
  </div>
   


  <div class="tab-pane fade" id="search">
     <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
      <th>Year</th>
      <th>Views</th>
      

    </tr>
  </thead>
  <tbody>
  {% for song in songs %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
      <td>{{song.year}}</td>
      <td>{{song.views}}</td>
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

  </div>

  
  <div class="tab-pane fade" id="playlist">
   
     <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm">Create Playlist</button>
     <!--button type="button" class="btn btn-danger btn-small" data-toggle="modal" data-target=".bs-example-modal-sm">Delete Playlist</button-->
     <hr>
   {% if playlists %}

     <ul>
     {% for p in playlists %}
      <li class="list-group-item">
    <span class="badge">{{p.songs.count}}</span>
    <a href="/getplaylist/{{p.pk}}">{{p.name}}</a>
  </li>
     {% endfor %}
  {% else %}
    <p>You haven't created any playlists!</p>
      {% endif %}

      <!-- Button trigger modal -->
     
      <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
                      <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      <h5 class="modal-title">Create Playlist</h5>
                    </div>
                    
                    <div class="modal-body">
                       <form method="post" action="/playlist/">
                       <div class="form-group">
                        <input type="text" class="form-control" placeholder="Playlist Name" name="name" required>
                    </div>
                    {% csrf_token %}
                   
                  
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          <button type="submit" class="btn btn-primary"><i>Done</i></button>
                        </div>
                      </form>
                    </div>
        </div>
      </div>

   </div>
  </div>

    <div class="tab-pane fade" id="friends">
{% if friends_feed %}
    <h2> Your friends recent activities</h2>

    <table class="table table-striped table-hover ">
  <thead>
    <tr class="success">
      <th>User</th>  
      <th>Song</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    {% for u in friends_feed %}
    <tr>
      <td id="{{u.song.pk}}">{{u.song|truncatewords:4}}</td>
      <td>{{u.user.username}}</td>
      <td>{{u.time}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
{% else %}
<h2>Follow some friends </h2>
{% endif %}
    </div>

</div>
</div>







<!--div class="col-md-4">
<div id="player">
<img src="" id="pic" class="img-rounded" alt="Rounded Image" style="min-height:300px;height:300px;">
<audio id="song" controls>
<source id="sound" src="" type="audio/mpeg">
</audio>
<h2 id="title"  class="text-success">Title</h2>
<h2 id="views" class="text-muted">views</h2>
<h2 id="artist" class="text-muted">Artist</h2>
<div id="success_result" class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <p><strong>successfully Added</strong></p>
</div>
<div class="btn-group">
    <a href="#" class="btn btn-default">+</a>
    <div class="btn-group">
      <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Add to playlist
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        {% for p in playlists %}
    <li><a name="playlist_name" id="{{p.pk}}" href="#">{{p.name}}</a></li>
  {% endfor %}
       </ul>
    </div>
  </div>
</div>
</div-->
<div class="col-md-4">
<div id="player">
<img src="" id="pic" class="img-rounded" alt="Rounded Image" style="min-height:300px;height:300px;">
<audio id="song" controls>
<source id="sound" src="" type="audio/mpeg">
</audio>
<h2 id="title"  class="text-success">Title</h2>
<h3 id="artist">Artist</h3>
<h2 id="views" class="text-muted">views</h2>
<div id="success_result" class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <p><strong>successfully Added</strong></p>
</div>
<div class="btn-group">
    <a href="#" class="btn btn-default">+</a>
    <div class="btn-group">
      <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Add to playlist
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        {% for p in playlists %}
    <li><a name="playlist_name" id="{{p.pk}}" href="#">{{p.name}}</a></li>
  {% endfor %}
       </ul>
    </div>
  </div>
</div>
</div>

<div id="userinfo"class="col-md-4">
 <div class="list-group">
  <h4  class="list-group-item active">
   My History {{user.name}}
  </h4>
 {% if playlists %} 
  <p class="list-group-item">{{playlists.count}} Playlists 
  </p>
  {% else %}
   <p class="list-group-item">No Playlists Created 
  </p>
  {% endif %}
  {% if userlog %}
  <p class="list-group-item">{{userlog.count}} Songs played till now</p>
 {% else %}
  <p class="list-group-item"> No  Songs played till now
  </p>
  {% endif %}
</div>
</div>
 





{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="row">
<div class="col-md-4">
<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
  {% csrf_token %}
  <label>User Name</label><br/>{{ form.username }}<br/>
  <label>Password </label><br/>{{ form.password}}<br/><br/>
  {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
  <input type="submit" class="btn btn-primary btn-sm" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>
</div>
</div>
{% endblock %}

templates/player.html
{% extends 'base.html' %}

{% block title %}
<title>Play -JukeBox</title>
{% endblock %}
{% block content %}
	<div class="col-md-8">
{% if songs%}
<h1>{{songs.count}} songs found</h1>
  <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
    
      

    </tr>
  </thead>
  <tbody>
  {% for song in songs %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>      
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
 
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

{% else %}
<h1>No results found</h1> 
{% endif %}

</div>


<div class="col-md-4">
<div id="player">
<img src="" id="pic" class="img-rounded" alt="Rounded Image" style="min-height:300px;height:300px;">
<audio id="song" controls>
<source id="sound" src="" type="audio/mpeg">
</audio>
<h2 id="title"  class="text-success">Title</h2>
<h3 id="artist">Artist</h3>
<h2 id="views" class="text-muted">views</h2>
</div>
</div>

<div id="userinfo" class="col-md-4">
 <div class="list-group">
  <h4  class="list-group-item active">
   My History {{user.name}}
  </h4>

  <p class="list-group-item">{{playlists.count}} Playlists 
  </p>
  <p class="list-group-item">57 Upvotes 
  </p>
  <p class="list-group-item">{{userlog.count}} Songs played till now</p>
</div>
</div>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}
<script src="{{STATIC_URL}}js/jquery.form.js"></script>
  <script src="{{STATIC_URL}}js/profile.js"></script>
  <title>Profile -SoundBox</title>
{% endblock %}



{% block content %}
<div class="col-md-8">

<ul class="nav nav-tabs">
  
  <li class="active"><a href="#search" data-toggle="tab">Find Friends</a></li>
  <li><a href="#home" data-toggle="tab">Following</a></li>
  <li><a href="#profile" data-toggle="tab">Followers</a></li>
  <li><a href="#history" data-toggle="tab">My History</a></li>
</ul>
<div id="myTabContent" class="tab-content">
 
  <div class="tab-pane fade active in" id="search">

 
          
                 <form id="form" type="get" action="/profile/"  role="search">
              <div class="form-group">
        <div class="input-group">
          <!--span class="input-group-addon">Search</span-->
          <input type="text" class="form-control" placeholder="Name or UserName or Email" name='q' required>
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit" autofocus><i>Find</i></button>
          </span>
        </div>
        </div>
              </form>
        <div id="results">
          {% if results %}
          {% for usr in results %}
              <div class="col-md-4"><div class="panel panel-success">
              <div class="panel-heading">
                <h3 class="panel-title">{{usr.username}}</h3></div>
              <div class="panel-body">
                <h4>{{usr.first_name.capitalize}} {{usr.last_name.capitalize}}</h4>
                {{usr.email}}<br/>
            <a name="follow" id="{{usr.pk}}" href="#" class="btn btn-primary btn-xs">Follow</a>
            </div>
            </div>
            </div>

          {% endfor %}
          {% endif %}
        </div>
     </div>




  <div class="tab-pane fade" id="home">

    {% if following %}

      {% for usr in following%}

      <div class="col-md-4"><div class="panel panel-success">
              <div class="panel-heading">
                <h3 class="panel-title">{{usr.user.username}}</h3></div>
              <div class="panel-body">
                <h4>{{usr.user.first_name.capitalize}} {{usr.user.last_name.capitalize}}</h4>
                {{usr.user.email}}<br/>
            <a name="follow" id="{{usr.pk}}" href="#" class="btn btn-primary btn-xs">Follow</a>
            </div>
            </div>
            </div>

      {% endfor %}

    {% else %}
    <h3 class="text-danger">You aren't following anyone!</h3>
    {% endif %}
    
  </div>
  <div class="tab-pane fade" id="profile">
    
    {% if followed %}

      {% for usr in followed %}

      <div class="col-md-4"><div class="panel panel-success">
              <div class="panel-heading">
                <h3 class="panel-title">{{usr.user.username}}</h3></div>
              <div class="panel-body">
                <h4>{{usr.user.first_name.capitalize}} {{usr.user.last_name.capitalize}}</h4>
                {{usr.user.email}}<br/>
            <a name="follow" id="{{usr.pk}}" href="#" class="btn btn-primary btn-xs">Follow</a>
            <a id="followed" href="#" class="btn btn-danger btn-xs">Following</a>
            </div>
            </div>
            </div>

      {% endfor %}

    {% else %}
    <h3 class="text-danger"> You have no follwers! </h3>
    {% endif %}
  </div>

     
   



   <div class="tab-pane fade" id="history">
    	<h3 class="text-success">Your last 10 songs</h3>
   	<table class="table table-striped table-hover ">
  <thead>
    <tr class="success">
      <th>Song</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    {% for h in history %}
    <tr>
      <td>{{h.song.title}}</td>
      <td>{{h.time}}</td>
    </tr>
    {% endfor %}
</tbody>
</table>

  </div>

</div>


</div>



{% endblock %}

templates/search/search.html
{% extends "base.html" %}

{% block title %}
  <title>Search -SoundBox</title>
{% endblock %}



{% block search %}
<div class="col-md-8">
{% if songs%}
<h1>{{songs.count}} songs found</h1>
  <table class="table  table-hover ">
  <thead>
    <tr class="success">
      
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Genre</th>
    
      

    </tr>
  </thead>
  <tbody>
  {% for song in songs %}
    <tr>
      
      <td id="{{song.pk}}">{{song.title|truncatewords:4}}</td>      
      <td>{{song.artist}}</td>
      <td>{{song.album}}</td>
      <td>{{song.genre}}</td>
 
      
    </tr> 
   {% endfor %}
  </tbody>
</table>

{% else %}
<h1>No results found</h1> 
{% endif %}

</div>


<div class="col-md-4">
<div id="player">
<img src="" id="pic" class="img-rounded" alt="Rounded Image" style="min-height:300px;height:300px;">
<audio id="song" controls>
<source id="sound" src="" type="audio/mpeg">
</audio>
<h2 id="title"  class="text-success">Title</h2>
<h3 id="artist">Artist</h3>
<h2 id="views" class="text-muted">views</h2>
</div>
</div>

<div id="userinfo" class="col-md-4">
 <div class="list-group">
  <h4  class="list-group-item active">
   My History {{user.name}}
  </h4>

  <p class="list-group-item">{{playlists.count}} Playlists 
  </p>
  <p class="list-group-item">57 Upvotes 
  </p>
  <p class="list-group-item">{{userlog.count}} Songs played till now</p>
</div>
</div>

  {% endblock %}